#include "visitors.h"
#include "../board/board.h"

_GetEnPassantMoveVisitor GetEnPassantMoveVisitor;
_IsCastlingMoveVisitor IsCastlingMoveVisitor;
_GetBasicMoveVisitor GetBasicMoveVisitor;
_GetMoveAddedValueVisitor GetMoveAddedValueVisitor;
_GetMovePointerVisitor GetMovePointerVisitor;
_DetermineIfMoveCanCaptureVisitor DetermineIfMoveCanCaptureVisitor;
